services:
  mariadb-repo:
    build: ./requirements/mariadb
    image: mariadb-repo
    container_name: mariadb-repo
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env
    # environment:
    #   - MARIADB_USER_PASS=/run/secrets/mariadb_user_pass
    #   - MARIADB_ROOT_PASS=/run/secrets/mariadb_root_pass
    # secrets:
    #   - mariadb_user_pass
    #   - mariadb_root_pass
    networks:
      - inception-network
    expose:
      - 3306

  wordpress-site:
    build: ./requirements/wordpress
    image: wordpress-site
    container_name: wordpress-site
    depends_on:
      - mariadb-repo
    env_file:
      - .env
    # environment:
    #   - CREDENTIALS=/run/secrets/credentials
    # secrets:
    #   - credentials
    volumes:
      - wp:/var/www/html
    restart: on-failure
    networks:
      - inception-network
    expose:
      - 9000

  nginx-server:
    build: ./requirements/nginx
    image: nginx-server
    container_name: nginx-server
    ports:
      - "443:443"
    depends_on:
      - wordpress-site
    restart: on-failure
    env_file:
      - .env
    networks:
      - inception-network
    volumes:
      - wp:/var/www/html
    expose:
      - "443:443"

networks:
  inception-network:
    name: inception-network

# secrets:
#   mariadb_user_pass:
#     file: ../secrets/db_password.txt
#   mariadb_root_pass:
#     file: ../secrets/db_root_password.txt
#   credentials:
#     file: ../secrets/credentials.txt

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/jocaetan/data/mysql
      o: bind

  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/jocaetan/data/html
      o: bind
